### ISSUE TITLE
Any VueJs Demo ?

### ISSUE THREAD

**Issue by abdulmanan7** [greymass/ual-anchor-demo#11]
I am very new to wax blockchain, I want to have a transaction using anchor.
Is there any demo or help for vuejs?
Thanks

**Comment by aaroncox** [comment]
For UAL specifically, not that we have worked with. I did a bit of searching and stumbled int this though, which hasn't been updated for some time:

https://github.com/Volentix/ual-vuejs-renderer

A renderer for UAL would need to be written like this for UAL to work in a VueJS application. Either that or you'll have to just integrate wallets directly. We do have at least one demo written in VueJS:

https://github.com/greymass/anchor-link-demo

**Comment by aaroncox** [comment]
Closing this out as a non-issue. 

If you have further questions on the above, feel free to start a forum thread on the topic in the community forums!

https://forums.eoscommunity.org/c/eosio-development/10
